<a href="https://colab.research.google.com/github/pvgandhi404/ECE-198-S.A.M.M./blob/main/Image_classifier_CIFAR_10_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix , classification_report
import numpy as np

In [ ]:
# x = image
# y = associated classification

(X_train, y_train), (X_test,y_test) = datasets.cifar10.load_data()
X_train.shape

(50000, 32, 32, 3)

In [ ]:
y_train = y_train.reshape(-1,)
y_train[:5]

array([6, 9, 9, 4, 1], dtype=uint8)

In [ ]:
y_test = y_test.reshape(-1,)

In [ ]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]
def plot_sample(X, y, index):
    plt.figure(figsize = (15,2))
    plt.imshow(X[index])
    plt.xlabel(classes[y[index]])

In [ ]:
# Normalize into rgb (max is 255)
X_train = X_train / 255.0
X_test = X_test / 255.0

In [ ]:
cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [ ]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
cnn.fit(X_train, y_train, epochs=15)

Epoch 1/15
1563/1563 [==============================] - 70s 45ms/step - loss: 1.2267 - accuracy: 0.5671
Epoch 2/15
1563/1563 [==============================] - 70s 45ms/step - loss: 1.0167 - accuracy: 0.6449
Epoch 3/15
1563/1563 [==============================] - 67s 43ms/step - loss: 0.9077 - accuracy: 0.6825
Epoch 4/15
1563/1563 [==============================] - 69s 44ms/step - loss: 0.8326 - accuracy: 0.7121
Epoch 5/15
1563/1563 [==============================] - 69s 44ms/step - loss: 0.7690 - accuracy: 0.7321
Epoch 6/15
1563/1563 [==============================] - 69s 44ms/step - loss: 0.7127 - accuracy: 0.7515
Epoch 7/15
1563/1563 [==============================] - 68s 44ms/step - loss: 0.6654 - accuracy: 0.7670
Epoch 8/15
1563/1563 [==============================] - 68s 43ms/step - loss: 0.6141 - accuracy: 0.7870
Epoch 9/15
1563/1563 [==============================] - 71s 45ms/step - loss: 0.5731 - accuracy: 0.7988
Epoch 10/15
1563/1563 [==============================] - 70s 44m

In [ ]:
cnn.evaluate(X_test,y_test)

313/313 [==============================] - 5s 15ms/step - loss: 1.1372 - accuracy: 0.6860


[1.1372051239013672, 0.6859999895095825]

In [ ]:
y_pred = cnn.predict(X_test)
y_pred[:5]

for i in range(0, 5):
  print(np.argmax(y_pred[i]))
  print(y_test[i])

313/313 [==============================] - 4s 13ms/step
3
3
8
8
8
8
0
0
6
6


In [ ]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]

[3, 8, 8, 0, 6]

In [ ]:
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)

In [ ]:
cnn.save("/content/drive/MyDrive/Machine Learning Code/Computer Vision/Rand Stuff/og_animal_15epoch")

In [ ]:
model = tf.keras.models.load_model("/content/drive/MyDrive/Machine Learning Code/Computer Vision/Rand Stuff/og_animal_15epoch")

In [ ]:
deertest = open("/content/deer6.png", 'rb')


import matplotlib.pyplot as plt
deer = plt.imread(deertest)

deer = deer / 255.0

print(deer)

deer.reshape(-1)

model.predict(deer)

[[[0.00315263 0.0028143  0.00226067]
  [0.00316801 0.00287582 0.00215302]
  [0.00315263 0.00295271 0.00236832]
  ...
  [0.00249135 0.00219915 0.00161476]
  [0.00279892 0.00250673 0.00199923]
  [0.00241446 0.00224529 0.0016609 ]]

 [[0.00327566 0.00307574 0.00236832]
  [0.00304498 0.0028143  0.00206075]
  [0.00270665 0.00239908 0.00176855]
  ...
  [0.00276817 0.00258362 0.00183007]
  [0.00278354 0.00258362 0.00198385]
  [0.00233756 0.0021684  0.00164552]]

 [[0.00301423 0.00275279 0.00207612]
  [0.00256824 0.00227605 0.00164552]
  [0.002599   0.00230681 0.00176855]
  ...
  [0.00299885 0.00272203 0.00195309]
  [0.00252211 0.00224529 0.00155325]
  [0.00242983 0.00218378 0.00167628]]

 ...

 [[0.00264514 0.00232218 0.00167628]
  [0.00287582 0.00247597 0.00173779]
  [0.00304498 0.00269127 0.00192234]
  ...
  [0.00273741 0.00239908 0.00170704]
  [0.00190696 0.00161476 0.00112265]
  [0.00249135 0.00227605 0.00176855]]

 [[0.00319877 0.00290657 0.00224529]
  [0.00301423 0.00264514 0.00190696]


ValueError: ignored